name = "youtube-tracker"
compatibility_date = "2025-03-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "youtube-tracker-db"
database_id = "fa0db19f-a523-4c52-984d-682e527820c9"
